### ISSUE TITLE
기분석 사전 문의드립니다.

### ISSUE THREAD

**Issue by hyeonmini** [puilp0502/khaiii.js#1]
안녕하세요! 만들어주신 덕분에 node.js 환경에서 [khaiii를 설치해 사용](https://www.dailyscrap.news/)할 수 있게 되었습니다. 감사드립니다.^^
khaiii에서 원래 지원하는 [기분석 사전](https://github.com/puilp0502/khaiii.js)을 어떻게 적용할 수 있을지 궁금하여 문의드립니다.

**Comment by puilp0502** [comment]
안녕하세요.
khaiii.js는 사용자의 편의를 위해 Khaiii 0.4 Base Model 리소스를 포함하지만, [Khaiii.initialize](https://github.com/puilp0502/khaiii.js#initializekhaiiiconfig-promisekhaiii) 함수에서 `resourceProvider`와 `resourceRoot` 인자를 사용해 khaiii.js가 사용할 리소스 디렉토리를 선택할 수 있습니다. 

Node.js 환경의 경우, `"nodefs"` 리소스 제공자를 사용하여 로컬 파일시스템의 리소스를 사용할 수 있습니다:
```js
let khaiii = await Khaiii.initialize({
    resourceProvider: "nodefs",
    resourceRoot: "<path-to-khaiii-resource-folder>",
})
```
khaiii.js가 사용하는 리소스의 형식은 khaiii와 동일하기에, [공식 문서](https://github.com/kakao/khaiii/wiki/%EA%B8%B0%EB%B6%84%EC%84%9D-%EC%82%AC%EC%A0%84)를 따라 리소스를 빌드한 다음 위 방식대로 khaiii.js로 로드하면 기분석 사전을 사용할 수 있을 것입니다.

**Comment by hyeonmini** [comment]
설명해주신 내용과 함께 공식 문서를 다시 확인해보니 이해하기 한결 수월했습니다.^^ 감사합니다!
